name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Salesforce
      run: sf org login jwt \--client-id ${{ secrets.SFDX_CLIENT_ID }} \--jwt-key-file ./server.key \--username ${{ secrets.SFDX_USERNAME }} \-a sfdx

    - name: Deploy changes
      run: sfdx force:source:deploy -p force-app/main/default -u sfdx --json

    # Add additional steps for validation, testing, etc.
